# Generated by Django 2.2.16 on 2020-10-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='nickname',
            field=models.CharField(default='default', max_length=30, verbose_name='Nickname'),
            preserve_default=False,
        ),
    ]
