# Generated by Django 2.2.16 on 2020-10-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201020_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='merchants/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='slug',
            field=models.SlugField(default='merchant1', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
