# Generated by Django 2.2.16 on 2020-10-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201021_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='merchant_website',
            field=models.URLField(blank=True),
        ),
    ]
