# Generated by Django 2.2.16 on 2020-10-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201025_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='merchant_street',
            field=models.CharField(default='218 Tech Rd', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='merchant_zip',
            field=models.CharField(default='15205', max_length=12),
            preserve_default=False,
        ),
    ]
