# Generated by Django 2.2.16 on 2020-10-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20201026_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='product_url',
            field=models.URLField(blank=True),
        ),
    ]
