# Generated by Django 2.2.16 on 2020-11-11 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20201019_1917'),
        ('account', '0011_merchantprofile_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='order',
            field=models.ForeignKey(blank=True, default=23, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
            preserve_default=False,
        ),
    ]
