# Generated by Django 2.2.16 on 2020-10-17 00:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201010_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_last_name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='merchant_email',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Merchant Name'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
